#!/usr/bin/env bash

sudo add-apt-repository -y ppa:yubico/stable
sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  hwdata \
  linux-tools-generic \
  pcscd \
  pinentry-gnome3 \
  scdaemon \
  yubikey-manager

