#!/usr/bin/env bash

curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
alias composer='/usr/local/bin/composer'
